export enum tagTypes {
  user = "user",
  department = "department",
  faculty = "faculty",
  admin = "admin",
  transaction = "transaction",
  vatrebatetype = "vatrebatetype",
  fiscalyearinfo = "fiscalyearinfo",
  vatrateref = "vatrateref",
  uomset = "uomset",
  uominfo = "uominfo",
  bankinfo = "bankinfo",
  bankaccounttype = "bankaccounttype",
  economicactivity = "economicactivity",
  vatregtype = "vatregtype",
  nav = "nav",
  vatpaymethod = "vatpaymethod",
  itemcategory = "itemcategory",
  currencyinfo = "currencyinfo",
  transsubtype = "transsubtype",
  vatmonthinfo = "vatmonthinfo",
  ReceiveLocalPurchase = "ReceiveLocalPurchase",
  accountcode = "accountcode",
  productcat = "productcat",
  producttype = "producttype",
  hscode = "hscode",
  vehicletype = " vehicletype",
  vatstructure = "vatstructure",
  area = "area",
  city = "city",
  languages = "languages",
  lcfor = "lcfor",
  importlcpurpose = "importlcpurpose",
  accountiteminfo = "accountiteminfo",
  paymentmode = "paymentmode",
  challantype = "challantype",
  addresstype = "addresstype",
  upazilla = "upazilla",
  division = "division",
  businessinformation = "businessinformation",
  areaofeconomicactivity= "areaofeconomicactivity",
  policestation= "policestation",
  documenttype= "documenttype",
  companytype= "companytype",
  currencyexchangerate = "currencyexchangerate",
  othersadjustmenttype = "othersadjustmenttype",
  rolemenus = "rolemenus",
  //Forhad
  vdspurchase = "vdspurchase",
  vdsseller = "vdsseller",
  vdspayment = "vdspayment",
  treasurychallan = "treasurychallan",
  otheradjustment = "otheradjustment",
  lastmonthcolum = "lastmonthcolum",
  duepenaltysercharge = "duepenaltysercharge",
  inventorymethod = "inventorymethod",
  bankbranch = "bankbranch",
  commisstionrate = "commisstionrate",
  debitnotefor = "debitnotefor",
  creditnotefor = "creditnotefor",
  vatratestage = "vatratestage",
  portinfo ="portinfo",
  receive="receive",
  supplierinfo="supplierinfo",
  vatratetype="vatratetype",
  district="district",
  country="country",
  companybranchinfo = "companybranchinfo",
  customersetup="customersetup",
  companyinfo ="companyinfo",
  companyemployee ="companyemployee",
  legaldocuments ="legaldocuments",
  sotemapping= "sotemapping",
  itemmaster= "itemmaster",
  
}

export const tagTypesList = [
  tagTypes.user,
  tagTypes.department,
  tagTypes.faculty,
  tagTypes.admin,
  tagTypes.transaction,
  tagTypes.nav,
  tagTypes.vatrebatetype,
  tagTypes.fiscalyearinfo,
  tagTypes.vatrateref,
  tagTypes.uomset,
  tagTypes.economicactivity,
  tagTypes.vatregtype,
  tagTypes.vatpaymethod,
  tagTypes.itemcategory,
  tagTypes.currencyinfo,
  tagTypes.transsubtype,
  tagTypes.vatmonthinfo,
  tagTypes.ReceiveLocalPurchase,
  tagTypes.accountcode,
  tagTypes.productcat,
  tagTypes.producttype,
  tagTypes.hscode,
  tagTypes.vehicletype,
  tagTypes.currencyexchangerate,
  tagTypes.vatstructure,
  tagTypes.othersadjustmenttype,
  tagTypes.businessinformation,
  tagTypes.areaofeconomicactivity,
  tagTypes.policestation,
  tagTypes.documenttype,
  tagTypes.rolemenus,
  tagTypes.companytype,
  //Forhad
  tagTypes.vdspurchase,
  tagTypes.vdsseller,
  tagTypes.vdspayment,
  tagTypes.treasurychallan,
  tagTypes.otheradjustment,
  tagTypes.lastmonthcolum,
  tagTypes.duepenaltysercharge,
  tagTypes.inventorymethod,
  tagTypes.bankbranch,
  tagTypes.commisstionrate,
  tagTypes.debitnotefor,
  tagTypes.creditnotefor,
  tagTypes.vatratestage,
  tagTypes.portinfo,
  tagTypes.area,
  tagTypes.city,
  tagTypes.languages,
  tagTypes.lcfor,
  tagTypes.importlcpurpose,
  tagTypes.receive,
  tagTypes.uominfo,
  tagTypes.supplierinfo,
  tagTypes.bankaccounttype,
  tagTypes.companybranchinfo,
  tagTypes.customersetup,
  tagTypes.vatratetype,
  tagTypes.bankinfo,
  tagTypes.paymentmode,
  tagTypes.challantype,
  tagTypes.addresstype,
  tagTypes.division,
  tagTypes.district,
  tagTypes.country,
  tagTypes.upazilla,
  tagTypes.accountiteminfo,
  tagTypes.companyinfo,
  tagTypes.companyemployee,
  tagTypes.legaldocuments,
  tagTypes.sotemapping,
  tagTypes.itemmaster
];
